
[core]
  arch = 0
  cert_path = "/tls/godev/godev.crt"
  host = "godev"
  os = 0
  port = 50051
  ssh_keys = []
  ssh_port = 0
  tkn = ""
  tkn_expiration = 1970-01-01T00:00:00Z
  tls = true

[log]
  file = "/home/nefix/.log/drlm/drlmctl.log"
  level = "info"

[plugin_repos]

  [plugin_repos.default]
    url = "https://github.com/brainupdaters/drlm-plugins"
